# This is a basic workflow to help you get started with Actions

name: DataFactory Full Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0

      - name: Install NPM packages
        run: |
          npm install 
          
      - name: Run Validation Against DF
        run: | 
          npm run build validate . ${{ secrets.DEV_DF }}
          
      - name: Export ARM Template
        run: |
          npm run build export . ${{ secrets.DEV_DF }} "ArmTemplates"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          path: ./ArmTemplates
          
          
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: 'Deploy DF to Azure environment'
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          # Artifact name
          name: artifact
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
           creds: ${{ secrets.CLIENT_ID }}
           
      - name: Echo repo contents
        run: |
          ls -a

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Provide the target region, only required for management Group or Subscription deployments.
          region: centralus
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: sully-db-ws-poc
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./artifact/ARMTemplateForFactory.json
