# This is a basic workflow to help you get started with Actions

name: DataFactory Deployment Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ adf_publish ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to Data Factory

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: adf_publish
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
           creds: ${{ secrets.CLIENT_ID }} 

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Provide the target region, only required for management Group or Subscription deployments.
          region: centralus
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: sully-db-ws-poc
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./sullydf/ARMTemplateForFactory.json

